# Generated by Django 3.0.8 on 2021-01-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='robo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('temp', models.IntegerField()),
                ('con_speed', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('camera', models.BooleanField()),
                ('ir', models.BooleanField()),
            ],
        ),
    ]
